### ISSUE TITLE
compare_and_set will not increment past 256 on JRuby

### ISSUE THREAD

**Issue by ileitch** [headius/ruby-atomic#19]
This is a strange one.

When I run the below code, it will not progress past 256. However If I set `current_seq` to 256 as returned by `@sequence.get` will continue. See the commented out line in the loop.

The output I see is `{:get=>256, :current_seq=>256, :new_seq=>257}`

Work as expected on Rubinius.

```
jruby 1.7.3 (1.9.3p385) 2013-02-21 dac429b on Java HotSpot(TM) 64-Bit Server VM 1.8.0-ea-b84 +indy [darwin-x86_64]
```

``` ruby
require 'rubygems'
require 'atomic'

class Sequence
  INITIAL_VALUE = 0

  def initialize(initial = INITIAL_VALUE)
    @sequence = Atomic.new(initial)
  end

  def get
    @sequence.get
  end

  def set(current_seq, new_seq)
    p [current_seq, new_seq]

    while !@sequence.compare_and_set(current_seq, new_seq)
      a = { :get => @sequence.get, :current_seq => current_seq, :new_seq => new_seq }
      p a

      # Uncomment this an it'll work.
      # current_seq = @sequence.get
    end
  end
end

s = Sequence.new(0)

300.times do |i|
  s.set(i, i + 1)
end
```

**Comment by headius** [comment]
Whether or not Fixnums are idempotent is entirely implementation-specific,
and you can't even rely on the range of idempotent values. MRI has
idempotent Fixnum up to 30 bits on a 32-bit build and 62 bits on on a
64-bit build. MRI 2.0.0 has idempotent Float values up to some range on
64-bit, as does Macruby, which has the same Fixnum range. JRuby has
idempotent Fixnums up to 8 bits. IronRuby may do similar. Topaz does not
have idempotent Fixnums or Floats. I believe Maglev has a similar range to
MRI but I am not sure.

I suggest that we add  AtomicInteger and AtomicFloat to handle the numeric
cases, since it is almost impossible to tell when numeric values will be
idempotent across versions.

**Comment by ileitch** [comment]
Without AtomicInteger, how can I implement a method, that given a value waits for the Atomic to reach value - 1?

``` ruby
def set(value)
  while !@atomic.compare_and_set(value-1, value); end
end
```

``` ruby
>> a = Atomic.new(255)
=> #<Atomic:0xffaa6af>
>> a.compare_and_set(255, 256)
=> true
>> a.compare_and_set(256, 257)
=> false
```

**Comment by headius** [comment]
I'm adding a special case for any Numeric types that will use a Ruby == plus normal CAS. It won't be as efficient as an AtomicInteger, etc, but it will make numerics work like most people expect.

**Comment by headius** [comment]
I have implemented the logic for JRuby and added some tests for at least Fixnums. More tests for other numeric types, as well as the same logic for the C ext, and we can call this fixed.

**Comment by headius** [comment]
Added some additional numeric tests in e59e92b.

**Comment by ileitch** [comment]
Awesome, thanks.

**Comment by headius** [comment]
@ileitch Note that it still needs an MRI impl, and as a result the @travisci builds are failing.

**Comment by headius** [comment]
I added Ruby impls of the numeric logic in ed84820.

atomic-1.1.8 is on rubygems.org.
