### ISSUE TITLE
Atomic array operations?

### ISSUE THREAD

**Issue by igrigorik** [headius/ruby-atomic#3]
> a = Atomic.new([])
> a.update {|v| v.push 1}

so far so good.. since v.push returns an array. But, how do you do an atomic shift operation?

> a.update {|v| v.shift} # this will update a to be the shifted value

I guess you can access the internal value via a.value, but then that kills the whole point of atomic?

**Comment by headius** [comment]
What you're doing here isn't actually atomic or thread-safe in any way. Atomic guarantees that updates to the reference it contains will be done atomically; if the object that reference points at is mutated, that's outside the scope of the library.

In order to make your version atomic, it would have to be:

 a = Atomic.new([])
 a.update {|v| v + [1]}

Possibly freezing the array after each replacement so it is not mutated. Note that without freezing, this does not guarantee the original array is not being mutated, so if there's a problem with concurrent mutate/read (for the + call) it can still break.

I understand the need for a thread-safe Array in Ruby, but Atomic is intended for Atomic updates to a given reference.

**Comment by igrigorik** [comment]
Ah, thanks for the clarification.
